#!/bin/bash
#
# Ensure that no commit breaks erjoalgo-stumpwmrc

OUTPUT=$(sbcl \
             --eval "(load \"lisp/erjoalgo-stumpwmrc.asd\")" \
             --eval "(require 'erjoalgo-stumpwmrc)" --non-interactive \
             2>&1 | tee /dev/stderr)

if test $? != 0; then
    echo "compilation failed!"
    exit ${LINENO}
elif grep -oP \
         "caught WARNING|undefined variable|Undefined function" \
         <<< "${OUTPUT}"; then
    echo "compilation warnings found!"
    exit ${LINENO}
fi

# Local Variables:
# mode: sh-mode
# End:
