#!/bin/bash -x

set -euo pipefail
#
# Ensure that no commit breaks erjoalgo-stumpwmrc

OUTPUT=$(sbcl \
             --eval "(load \"lisp/erjoalgo-stumpwmrc.asd\")" \
             --eval "(require 'erjoalgo-stumpwmrc)" --non-interactive \
             2>&1 | tee /dev/stderr)

if grep -oP \
        "caught WARNING|undefined variable|Undefined function" \
        <<< "${OUTPUT}"; then
    echo "compilation warnings found!"
    exit ${LINENO}
fi

if command -v sh-fix-getopt.el; then
    sh-fix-getopt.el ./scripts/*/*
fi


# Local Variables:
# mode: sh-mode
# End:
