#!/bin/bash

set -euo pipefail

USAGE=false
HTPASSWD_FILE=""
HTPASSWD_OPTS=""

while getopts "hf:n:o:" OPT; do
    case ${OPT} in
    f)
        HTPASSWD_FILE=${OPTARG}
        ;;
    h)
        USAGE=true
        ;;
    n)
        LEN=${OPTARG}
        ;;
    o)
        HTPASSWD_OPTS=${OPTARG}
        ;;
    esac
done

shift $(($OPTIND - 1))

if test ${USAGE} = true -o -z "${HTPASSWD_FILE}"; then
    echo "usage: $(basename ${0}) -f HTPASSWD_FILE [ -o ${HTPASSWD_OPTS}  ] [ USER...  ]"
    exit 1
fi

LEN=${LEN:-8}

function genpasswd {
    LEN=${1:-16}
    tr -dc A-Za-z0-9_ < /dev/urandom  \
        | head -c ${LEN} \
        | tr -d ' '  \
        || true # prevent SIGPIPE from causing 141 exit code
}

test -e ${HTPASSWD_FILE} || touch ${HTPASSWD_FILE}
for USER in $*; do
    PASS=$(genpasswd ${LEN})
    echo "adding ${USER} => ${PASS}"
    # still fails on non-zero exit
    htpasswd -i ${HTPASSWD_OPTS} ${HTPASSWD_FILE} ${USER} <<< "${PASS}" 2>/dev/null
done
