`(
  (("Iceweasel" "Navigator" "Firefox" wwww-browser "Chromium")
   ("F2" (send-meta-key (current-screen) (kbd "C-TAB")))
   ("F1" (send-meta-key (current-screen) (kbd "C-ISO_Left_Tab")))
   ("F4" (send-meta-key (current-screen) (kbd "C-F4")))
   ("S-F4" (send-meta-key (current-screen) (kbd "C-T")))
   ("F3" (send-meta-key (current-screen) (kbd "C-f")) (send-meta-key (current-screen) (kbd "C-g")) )
   ;;("S-F4" (send-meta-key (current-screen) (kbd "C-S-F4")))
   ("F9" (send-meta-key (current-screen) (kbd "C--")))
   ("F10" (send-meta-key (current-screen) (kbd "C-=")))
   ("M-F1" (run-shell-command "xdotool key alt+Left"))
   ("M-F2" (run-shell-command "xdotool key alt+Right"))

   ("S-F1" (send-meta-key (current-screen) (kbd "C-S-SunPageUp")))
   ("S-F2" (send-meta-key (current-screen) (kbd "C-S-SunPageDown")))

   ;;("d" (send-meta-key (current-screen) (kbd "SunPageDown")))
   
   ;;("w" (send-meta-key (current-screen) (kbd "SunPageUp")))
   ;;("a" (send-meta-key (current-screen) (kbd "Left")))
   ;;("s" (send-meta-key (current-screen) (kbd "Right")))
   
   )

  (("x-terminal-emulator" "X-terminal-emulator" "roxterm" "Roxterm")
   ("SunPageUp" (send-meta-key (current-screen) (kbd "S-SunPageUp")) (echo "sunpageup"))
   ("SunPageDown" (send-meta-key (current-screen) (kbd "S-SunPageDown")) (echo "sunpagedown"))
					;("F1" (send-meta-key (current-screen) (kbd "C-ISO_Left_Tab")))
					;("F4" (send-meta-key (current-screen) (kbd "C-F4")))
					;("M-F1" (send-meta-key (current-screen) (kbd "M-Left")))
   )

  (("Evince" "evince")
   ;;("d" (send-meta-key (current-screen) (kbd "Down")))
   ;;("w" (send-meta-key (current-screen) (kbd "Up")))
   ;;("a" (send-meta-key (current-screen) (kbd "Left")))
   ;;("s" (send-meta-key (current-screen) (kbd "Right")))
   ;;("g" (send-meta-key (current-screen) (kbd "C-l")))
   ;;("n" (send-meta-key (current-screen) (kbd "C-SunPageDown")))
   ;;("p" (send-meta-key (current-screen) (kbd "C-SunPageUp")))
   ("F3" (send-meta-key (current-screen) (kbd "C-f")))
   ("-" (send-meta-key (current-screen) (kbd "C--")))
   ("+" (send-meta-key (current-screen) (kbd "C-+")))
   )
  ;;(("Zathura" "zathura")
  
  ;;("SunPageUp" (echo "hola4") (send-meta-key (current-screen) (kbd "S-SunPageUp")) (run-shell-command "xdotool key shift+Prior" t) )
  ;;("SunPageDown" (send-meta-key (current-screen) (kbd "S-SunPageUp")) (run-shell-command "xdotool key shift+Next"))
  ;;("F1" (send-meta-key (current-screen) (kbd "C-ISO_Left_Tab")))
  ;;("F4" (send-meta-key (current-screen) (kbd "C-F4")))
  )
