(define-search-engines
    '(
      ("d" "ddg" "https://duckduckgo.com/lite/?q=~A")
      ("w" "wiki" "https://en.wikipedia.org/w/index.php?search=~A")
      ("y" "youtube" "https://www.youtube.com/results?search_query=~A")
      ("s" "soverflow" "http://stackoverflow.com/search?q=~A")
      ("b" "bingimg" "http://www.bing.com/images/search?q=~A")
      ("b" "bingimg" "https://www.google.com/search?tbm=isch&q=~A")
      ("w" "wordreference" "http://www.wordreference.com/es/translation.asp?tranword=~A")
      ("e" "ebay" "http://www.ebay.com/sch/i.html?&_nkw=~A")
      ("l" "localhost" "http://localhost:~A")
      ("G" "github" "https://github.com/search?utf8=%E2%9C%93&q=~A")
      ("p" "google-maps" "https://www.google.com/maps/search/~A")
      ("r" "word-reference" "http://www.wordreference.com/es/translation.asp?tranword=~A")
      ("B" "baidu" "https://www.baidu.com/s?wd=~A")
      ("R" "spanishdict" "http://www.spanishdict.com/examples/~A")
      ("L" "linguee" "https://www.linguee.com/english-spanish/search?source=auto&query=~A")
      ("g" "google" "https://www.google.com/search?num=20&q=~A")
      ("m" "moma" "https://moma.corp.google.com/search?q=~A")
      ("m" "mvnrepository" "http://mvnrepository.com/search?q=~A")
      ("W" "Who" "https://moma.corp.google.com/person/~A")
      ("Y" "Yaqs" "https://yaqs.googleplex.com/eng?query=~A")
      ("c" "codesearch" "https://cs.corp.google.com/?q=~A")
      ("t" "contacts" "http://localhost:1959/contacts")
      ("z" "amazon" "https://www.amazon.com/s?k=~A")
      ("f" "whole-foods" "https://www.amazon.com/s?i=wholefoods&k=~A")
      ("h" "home-depot" "https://www.homedepot.com/s/~A")
      ("H" "lowes" "https://www.lowes.com/search?searchTerm=~A")))
