#!/bin/bash -x

set -euo pipefail

SELFD="$(dirname $(realpath $0))"

URL=https://github.com/erjoalgo/openssh-portable
LOCAL_REPO=${HOME}/git/$(basename "${URL}")

if ! test -d "${LOCAL_REPO}"; then
    git clone -o fork ${URL} "${LOCAL_REPO}"
    git remote add upstream https://github.com/openssh/openssh-portable
    git fetch upstream
fi

cd "${LOCAL_REPO}"

git fetch fork
git checkout non-debian
if git pull fork --ff-only non-debian; then
    echo "WARN: pull failed."
fi

sudo apt-get update
sudo apt-get install -y autoconf libcrypto++-dev libssl-dev

make clean
if test -e ./ssh; then
    rm ./ssh
fi

if ! ( autoreconf && ./configure && make ) && test -e ./ssh; then
    echo "warn: proceeding on build failure since ./ssh was built"
fi


SSH=$(which ssh)
test -e ./ssh
sudo mv "${SSH}" "${SSH}.debian"
sudo mv ./ssh "${SSH}"

# Local Variables:
# mode: sh-mode
# mode: sh-mode
# End:
