backend = "glx";

invert-color-include = [
    "class_g = 'Chromium'",
    "class_g = 'matplotlib'",
    "class_g = 'OpenSCAD'",
    "class_g = 'Zathura'",
    "class_g = 'Xournal'",
    "class_g = 'TelegramDesktop'",
    "class_g = 'qimgv'",
    "class_g = 'Gsmartcontrol'",
    "class_g = 'firefox-esr'",
    "class_g = 'Pavucontrol'",
    "class_g = 'pavucontrol'",
    "class_g = 'Creality'",
    "class_g = 'Wireshark'",
    "class_g = 'Tor Browser'",
    "class_g = 'Evince'",
    "class_g = 'PrusaSlicer'",
    "class_g = 'Cura'",
    "class_g = 'cura'",
    "class_g = 'Com.github.xournalpp.xournalpp'",
];
