#!/bin/bash -x

set -euo pipefail

SELFD="$(dirname $(realpath $0))"

sudo apt-get install -y devscripts quilt

cd $(mktemp -d)
apt-get source openssh-client
PATCHES=$(echo $(pwd)/openssh-*/debian/patches)
test -d "${PATCHES}"
SERIES="${PATCHES}/series"
test -e "${SERIES}"
pushd .

if false; then
    cd $(mktemp -d)
    GIT_URL=https://github.com/erjoalgo/openssh-portable
    git clone "${GIT_URL}"
    cd $(basename "${GIT_URL}")
    TMPDIR=$(mktemp -d)
    git format-patch 22caa1d4bbc265f8f8970a7933798a7a067c7c3e^ --output-directory "${TMPDIR}"
    PATCH_FILENAME=$(echo ${TMPDIR}/*patch)
else
    PATCH_FILENAME="${SELFD}/patches/0001-Add-support-for-the-special-RANDOM-environment-varia.patch"
fi

pwd
test -e "${PATCH_FILENAME}"
cp "${PATCH_FILENAME}" "${PATCHES}"
echo $(basename "${PATCH_FILENAME}") >> "${PATCHES}/series"

popd

SOURCE_TREE=$(find . -maxdepth 1 -mindepth 1 -type d)
cd "${SOURCE_TREE}"

sudo apt-get -y build-dep openssh-client dgit

quilt push
quilt refresh

rm -f debian/changelog.dch
EMAIL=erjoalgo.com dch -n "Apply manual patch: $(basename ${PATCH_FILENAME})".

dpkg-buildpackage -us -uc

sudo dpkg -i ../ssh_8.4p1-5+deb11u1_all.deb

# Local Variables:
# mode: sh-mode
# End:
