#!/bin/bash -x

set -euo pipefail

# WIP
sudo apt-get install -y autossh

while getopts "ha:" OPT; do
    case ${OPT} in
    a)
        SOMEARG=${OPTARG}
        ;;
    h)
        less $0
        exit 0
        ;;
    esac
done
shift $((OPTIND -1))

sudo insert-text-block '# YBhmitLFbimkywNqu0jXW996vavpPrtP-autossh'  \
     /etc/systemd/system/autossh.service <<EOF
[Unit]
Description=Auto Reverse SSH
# Requires=systemd-networkd-wait-online.service
# After=systemd-networkd-wait-online.service

[Service]
# ExecStart=/usr/bin/autossh -f rpi
ExecStart=/usr/bin/autossh -M 0 -o "ExitOnForwardFailure=yes" -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -NR ${REMOTE_SSH_PORT}:127.0.0.1:${LOCAL_SSH_PORT} ${SSH_USER_HOST} -i /home/ealfonso/.ssh/id_rsa -p4410

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl enable autossh.service
sudo systemctl daemon-reload
sudo service autossh start


# Local Variables:
# mode: sh-mode
# End:
