#!/bin/bash -x

set -euo pipefail

#!/bin/bash -x

set -euo pipefail

install-xdg-open-handler.sh  \
    -c "linphone-dial.sh -t %u"  \
    -s tel  \
    -b "fkp6YNbFENtRk4L1uwh2F43Wa59R0gGh-xdg-open-tel-linphone"

# test:
sh -x $(which xdg-open) "tel:4443"

# Local Variables:
# mode: sh-mode
# End:
